### ISSUE TITLE
Experimental equipment

### ISSUE THREAD

**Issue by QingWind6** [j-min/HiREST#2]
Hello, I am very interested in your work, may I ask what equipment you completed the experiment on? I wonder if a 4090 will be enough?

**Comment by j-min** [comment]
As mentioned in #1 and https://github.com/j-min/HiREST/blob/main/README.md#training-on-single-gpu,
for the joint model training, we used a single 1080 Ti GPU with 11GB memory. So yes, a 4090 would be enough!
