### ISSUE TITLE
Can you kindly provide download_videos.py?

### ISSUE THREAD

**Issue by tuyunbin** [j-min/HiREST#3]
Hi Dr. Cho, I did not find the file of download_videos.py in the current code. Can you kindly provide this file or the videos used in your dataset? Thanks!

**Comment by aszala** [comment]
I've just uploaded the script used to download the videos from YouTube [here](https://github.com/j-min/HiREST/blob/main/extraction/video_features/download_videos.py).

**Comment by tuyunbin** [comment]
Hi, aszala, can you kindly provide the downloaded videos for me via online driver. Due to the internet policy, it is difficult for me to download the many videos from youtube. Thanks!

**Comment by j-min** [comment]
Hi @tuyunbin. I understand your concern; it took a long time for us to download the videos from YouTube.
However, unfortunately, we also can't host the original YouTube video files due to a lack of ample data storage in our academic lab resources and potential copyright issues.
