### ISSUE TITLE
[SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:2570)

### ISSUE THREAD

**Issue by missTL** [j-min/HiREST#5]
![image](https://github.com/j-min/HiREST/assets/98095885/d8a821c3-bf1a-42f5-bf56-3eebcc27eb12)
Run    bash scripts/run.sh --train       an error in your environment

**Comment by aszala** [comment]
I am not able to reproduce your error.

Did you follow all the instructions to create/setup the Python environment and download the data/weights?
